### ISSUE TITLE
Import to GPA 3.4: "no new logic nodes found"

### ISSUE THREAD

**Issue by leimer** [daniel-kun/Albuschat.LogicNodes#1]
Hi Daniel, today I tried to import your WebRequest logic node into GPA 3.4. Unfortunately the software showed me the error message "no new logic nodes found".

I looked into your package and compared it to the ones provided on the knx-user-forum e.g. https://service.knx-user-forum.de/?comm=download&id=20000010 . I recognized a difference in the specification of the PackageId inside of the Manifest.json

https://github.com/daniel-kun/Albuschat.LogicNodes/blob/master/Albuschat.LogicNodes.WebRequest/Manifest.json#L13

In your file there are curly braces ``{`` included, in the ones I compared, there where none of these present.

I changed the PackageId myself, to the probable desired format, and was able to import it into GPA. It was also possible to use it in the logic sheets and configure it as expected. In the end I tried to send it to the X1. Unfortunately the Manifest.json is also one of the signed files.
The X1 checked the files and detected my change to the Manifest.json and showed me an error message about that.

Would you mind publishing your WebRequest package with that slightly modified PackageId again?

P.S. if you would like to communicate in German, wäre das für mich auch okay ;-)

**Comment by leimer** [comment]
Hi Daniel, thanks for your reply. I downloaded your package from your Github release list.
https://github.com/daniel-kun/Albuschat.LogicNodes/releases/download/webrequest-3.0.1/d_albuschat_gmail_com.logic.Nodes.WebRequest-3.0.1.zip

To be sure I don't have any clutter inside my GPA, I will do the import today evening again, but use a different computer. I'll also take screenshots of all error messages I encounter. Expect to hear from me around 8pm CEST this day.

Regards, Johannes

**Comment by leimer** [comment]
Hi @daniel-kun,
I am really sorry. For some reason my GPA now imported your WebRequest-Release. I just used the same file I downloaded four days ago, which was formerly rejected. I have no clue, why it is working now. On the X1 my short testing logic also works, so everything is fine.
Sorry for the noise.
Regards, Johannes

**Comment by daniel-kun** [comment]
Thanks, I'm glad that it works now! If you don't mind I'd be happy to know in what way you are using the logic nodes - what are the use cases that are enabled by them? You can also reach me at d.albuschat@gmail.com.
