### ISSUE TITLE
Logikbaustein kostenpflichtig?

### ISSUE THREAD

**Issue by laserir** [daniel-kun/Albuschat.LogicNodes#2]
Habe soeben den Logikbaustein (3.0.1) in den GPA 4.1 importiert. Import hat geklappt, "Web Request" taucht in der Bibliothek auf.

Bei dem Versuch es auf das Logikblatt zu ziehen kommt die Meldung "Der Baustein Web Request konnte nicht erstellt werden." Die Info sagt "Lizenztyp: Lizenz erforderlich" im Gegensatz zu den anderen Bausteinen wo "Lizenztyp kostenfrei" steht.

Muss ich den Baustein im Gira Appshop kaufen?!

**Comment by daniel-kun** [comment]
Hallo "laserir",

die Bausteine sind im Gira AppShop kostenfrei beziehbar, hier ein Link zum WebRequest-Baustein:
https://appshop.gira.de/de/app/564.

Hier ist eine Anleitung, wie der kostenfreie Bezug einer Lizenz funktioniert (leider etwas umständlich):
https://appshop.gira.de/de/app/565

Melde dich gerne hier noch einmal, wenn du dabei Probleme hast.
Gruß! Daniel

**Comment by laserir** [comment]
Dankeschön :)
